export type LanguageOption = {
  code: string
  label: string
  googleCode: string
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'af', label: 'Afrikaans', googleCode: 'af' },
  { code: 'ak', label: 'Akan', googleCode: 'ak' },
  { code: 'sq', label: 'Shqip', googleCode: 'sq' },
  { code: 'am', label: 'አማርኛ', googleCode: 'am' },
  { code: 'ar', label: 'العربية', googleCode: 'ar' },
  { code: 'hy', label: 'Հայերեն', googleCode: 'hy' },
  { code: 'az', label: 'Azərbaycanca', googleCode: 'az' },
  { code: 'eu', label: 'Euskara', googleCode: 'eu' },
  { code: 'be', label: 'Беларуская', googleCode: 'be' },
  { code: 'bem', label: 'ChiBemba', googleCode: 'bem' },
  { code: 'bn', label: 'বাংলা', googleCode: 'bn' },
  { code: 'bh', label: 'भोजपुरी', googleCode: 'bh' },
  { code: 'xx-bork', label: 'Bork, bork, bork!', googleCode: 'xx-bork' },
  { code: 'bs', label: 'Bosanski', googleCode: 'bs' },
  { code: 'br', label: 'Brezhoneg', googleCode: 'br' },
  { code: 'bg', label: 'Български', googleCode: 'bg' },
  { code: 'km', label: 'ខ្មែរ', googleCode: 'km' },
  { code: 'ca', label: 'Català', googleCode: 'ca' },
  { code: 'chr', label: 'ᏣᎳᎩ', googleCode: 'chr' },
  { code: 'ny', label: 'Chichewa', googleCode: 'ny' },
  { code: 'zh-CN', label: '简体中文', googleCode: 'zh-CN' },
  { code: 'zh-TW', label: '繁體中文', googleCode: 'zh-TW' },
  { code: 'co', label: 'Corsu', googleCode: 'co' },
  { code: 'hr', label: 'Hrvatski', googleCode: 'hr' },
  { code: 'cs', label: 'Čeština', googleCode: 'cs' },
  { code: 'da', label: 'Dansk', googleCode: 'da' },
  { code: 'nl', label: 'Nederlands', googleCode: 'nl' },
  { code: 'xx-elmer', label: 'Elmer Fudd', googleCode: 'xx-elmer' },
  { code: 'en', label: 'English', googleCode: 'en' },
  { code: 'eo', label: 'Esperanto', googleCode: 'eo' },
  { code: 'et', label: 'Eesti', googleCode: 'et' },
  { code: 'ee', label: 'Eʋegbe', googleCode: 'ee' },
  { code: 'fo', label: 'Føroyskt', googleCode: 'fo' },
  { code: 'tl', label: 'Filipino', googleCode: 'tl' },
  { code: 'fi', label: 'Suomi', googleCode: 'fi' },
  { code: 'fr', label: 'Français', googleCode: 'fr' },
  { code: 'fy', label: 'Frysk', googleCode: 'fy' },
  { code: 'gaa', label: 'Ga', googleCode: 'gaa' },
  { code: 'gl', label: 'Galego', googleCode: 'gl' },
  { code: 'ka', label: 'ქართული', googleCode: 'ka' },
  { code: 'de', label: 'Deutsch', googleCode: 'de' },
  { code: 'el', label: 'Ελληνικά', googleCode: 'el' },
  { code: 'gn', label: 'Avañeʼẽ', googleCode: 'gn' },
  { code: 'gu', label: 'ગુજરાતી', googleCode: 'gu' },
  { code: 'xx-hacker', label: 'H4x0r', googleCode: 'xx-hacker' },
  { code: 'ht', label: 'Kreyòl Ayisyen', googleCode: 'ht' },
  { code: 'ha', label: 'Hausa', googleCode: 'ha' },
  { code: 'haw', label: 'ʻŌlelo Hawaiʻi', googleCode: 'haw' },
  { code: 'iw', label: 'עברית', googleCode: 'iw' },
  { code: 'hi', label: 'हिन्दी', googleCode: 'hi' },
  { code: 'hu', label: 'Magyar', googleCode: 'hu' },
  { code: 'is', label: 'Íslenska', googleCode: 'is' },
  { code: 'ig', label: 'Igbo', googleCode: 'ig' },
  { code: 'id', label: 'Bahasa Indonesia', googleCode: 'id' },
  { code: 'ia', label: 'Interlingua', googleCode: 'ia' },
  { code: 'ga', label: 'Gaeilge', googleCode: 'ga' },
  { code: 'it', label: 'Italiano', googleCode: 'it' },
  { code: 'ja', label: '日本語', googleCode: 'ja' },
  { code: 'jw', label: 'Basa Jawa', googleCode: 'jw' },
  { code: 'kn', label: 'ಕನ್ನಡ', googleCode: 'kn' },
  { code: 'kk', label: 'Қазақ тілі', googleCode: 'kk' },
  { code: 'rw', label: 'Kinyarwanda', googleCode: 'rw' },
  { code: 'rn', label: 'Ikirundi', googleCode: 'rn' },
  { code: 'xx-klingon', label: 'Klingon', googleCode: 'xx-klingon' },
  { code: 'kg', label: 'Kikongo', googleCode: 'kg' },
  { code: 'ko', label: '한국어', googleCode: 'ko' },
  { code: 'kri', label: 'Krio', googleCode: 'kri' },
  { code: 'ku', label: 'Kurdî', googleCode: 'ku' },
  { code: 'ckb', label: 'کوردیی ناوەندی', googleCode: 'ckb' },
  { code: 'ky', label: 'Кыргызча', googleCode: 'ky' },
  { code: 'lo', label: 'ລາວ', googleCode: 'lo' },
  { code: 'la', label: 'Latina', googleCode: 'la' },
  { code: 'lv', label: 'Latviešu', googleCode: 'lv' },
  { code: 'ln', label: 'Lingála', googleCode: 'ln' },
  { code: 'lt', label: 'Lietuvių', googleCode: 'lt' },
  { code: 'loz', label: 'Silozi', googleCode: 'loz' },
  { code: 'lg', label: 'Luganda', googleCode: 'lg' },
  { code: 'ach', label: 'Luo', googleCode: 'ach' },
  { code: 'mk', label: 'Македонски', googleCode: 'mk' },
  { code: 'mg', label: 'Malagasy', googleCode: 'mg' },
  { code: 'ms', label: 'Bahasa Melayu', googleCode: 'ms' },
  { code: 'ml', label: 'മലയാളം', googleCode: 'ml' },
  { code: 'mt', label: 'Malti', googleCode: 'mt' },
  { code: 'mi', label: 'Māori', googleCode: 'mi' },
  { code: 'mr', label: 'मराठी', googleCode: 'mr' },
  { code: 'mfe', label: 'Kreol Morisien', googleCode: 'mfe' },
  { code: 'mo', label: 'Moldovenească', googleCode: 'mo' },
  { code: 'mn', label: 'Монгол', googleCode: 'mn' },
  { code: 'sr-ME', label: 'Crnogorski', googleCode: 'sr-ME' },
  { code: 'ne', label: 'नेपाली', googleCode: 'ne' },
  { code: 'pcm', label: 'Naijá Pidgin', googleCode: 'pcm' },
  { code: 'nso', label: 'Sesotho sa Leboa', googleCode: 'nso' },
  { code: 'no', label: 'Norsk', googleCode: 'no' },
  { code: 'nn', label: 'Norsk Nynorsk', googleCode: 'nn' },
  { code: 'oc', label: 'Occitan', googleCode: 'oc' },
  { code: 'or', label: 'ଓଡିଆ', googleCode: 'or' },
  { code: 'om', label: 'Oromoo', googleCode: 'om' },
  { code: 'ps', label: 'پښتو', googleCode: 'ps' },
  { code: 'fa', label: 'فارسی', googleCode: 'fa' },
  { code: 'xx-pirate', label: 'Pirate', googleCode: 'xx-pirate' },
  { code: 'pl', label: 'Polski', googleCode: 'pl' },
  { code: 'pt-BR', label: 'Português (Brasil)', googleCode: 'pt-BR' },
  { code: 'pt-PT', label: 'Português (Portugal)', googleCode: 'pt-PT' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', googleCode: 'pa' },
  { code: 'qu', label: 'Quechua', googleCode: 'qu' },
  { code: 'ro', label: 'Română', googleCode: 'ro' },
  { code: 'rm', label: 'Rumantsch', googleCode: 'rm' },
  { code: 'nyn', label: 'Runyakitara', googleCode: 'nyn' },
  { code: 'ru', label: 'Русский', googleCode: 'ru' },
  { code: 'gd', label: 'Gàidhlig', googleCode: 'gd' },
  { code: 'sr', label: 'Српски', googleCode: 'sr' },
  { code: 'sh', label: 'Srpskohrvatski', googleCode: 'sh' },
  { code: 'st', label: 'Sesotho', googleCode: 'st' },
  { code: 'tn', label: 'Setswana', googleCode: 'tn' },
  { code: 'crs', label: 'Kreol Seselwa', googleCode: 'crs' },
  { code: 'sn', label: 'ChiShona', googleCode: 'sn' },
  { code: 'sd', label: 'سنڌي', googleCode: 'sd' },
  { code: 'si', label: 'සිංහල', googleCode: 'si' },
  { code: 'sk', label: 'Slovenčina', googleCode: 'sk' },
  { code: 'sl', label: 'Slovenščina', googleCode: 'sl' },
  { code: 'so', label: 'Soomaali', googleCode: 'so' },
  { code: 'es', label: 'Español', googleCode: 'es' },
  { code: 'es-419', label: 'Español (Latinoamérica)', googleCode: 'es-419' },
  { code: 'su', label: 'Basa Sunda', googleCode: 'su' },
  { code: 'sw', label: 'Kiswahili', googleCode: 'sw' },
  { code: 'sv', label: 'Svenska', googleCode: 'sv' },
  { code: 'tg', label: 'Тоҷикӣ', googleCode: 'tg' },
  { code: 'ta', label: 'தமிழ்', googleCode: 'ta' },
  { code: 'tt', label: 'Татарча', googleCode: 'tt' },
  { code: 'te', label: 'తెలుగు', googleCode: 'te' },
  { code: 'th', label: 'ไทย', googleCode: 'th' },
  { code: 'ti', label: 'ትግርኛ', googleCode: 'ti' },
  { code: 'to', label: 'Lea fakatonga', googleCode: 'to' },
  { code: 'lua', label: 'Tshiluba', googleCode: 'lua' },
  { code: 'tum', label: 'ChiTumbuka', googleCode: 'tum' },
  { code: 'tr', label: 'Türkçe', googleCode: 'tr' },
  { code: 'tk', label: 'Türkmençe', googleCode: 'tk' },
  { code: 'tw', label: 'Twi', googleCode: 'tw' },
  { code: 'ug', label: 'Uyƣurqə', googleCode: 'ug' },
  { code: 'uk', label: 'Українська', googleCode: 'uk' },
  { code: 'ur', label: 'اردو', googleCode: 'ur' },
  { code: 'uz', label: 'Oʻzbekcha', googleCode: 'uz' },
  { code: 'vi', label: 'Tiếng Việt', googleCode: 'vi' },
  { code: 'cy', label: 'Cymraeg', googleCode: 'cy' },
  { code: 'wo', label: 'Wolof', googleCode: 'wo' },
  { code: 'xh', label: 'isiXhosa', googleCode: 'xh' },
  { code: 'yi', label: 'ייִדיש', googleCode: 'yi' },
  { code: 'yo', label: 'Yorùbá', googleCode: 'yo' },
  { code: 'zu', label: 'isiZulu', googleCode: 'zu' },
]

